### PR TITLE
Feature/show task description

### LINKED ISSUE #94: Show task description on DDF
Introduction: To enhance the User Experience of the MyBit DDF we want to implement the ability for users to see task descriptions right from the DDF layer, without having to navigate to Github. 

Requirements:
1. Design and implement a view description button in a clear but not intrusive method on the current DDF design for each individual task.
2. Design and implement expanding functionality to display the task description with an overflow mechanism if the task is too long.
3. Have a dynamic bridge between the DDF and Github (page refreshes every 30 seconds by default) so descriptions are automatically updated on the DDF layer if updated on Github.

To Submit:
1. Comment on task with a testing URL to get approval for design and placement.
2. Please submit a pull request with the final version including all functionality once complete.

Disclaimer
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by cryptomental**
Fixes #94 

Running live at http://51.75.66.221:3000/

desc

It is possible to show/hide each description individually, default is to hide.

Dependencies: github-proxy , PR link will be added.

### CODE REVIEW

**Comment by cryptomental** [comment]
Dependency: https://github.com/MyBitFoundation/github-proxy/pull/27

**Comment by jjperezaguinaga** [comment]
@cryptomental Looking good! Let me give a try to the current setup with your updated code from GitHub proxy 😊

**Comment by cryptomental** [comment]
@jjperezaguinaga great! I removed last commit from the pull request, the one that switches the proxy. If you would like to use my proxy from the pull request just apply this change in api/github.js : 

```
commit 8d0d2a0de6d06f04e920b5b0e000f49986e304c5
Author: Cryptomental <cryptomental.com@gmail.com>
Date:   Fri Nov 30 22:50:16 2018 +0100

    api/github: Point to a temporary github-proxy.

    Refs: https://github.com/MyBitFoundation/MyBit-DDF.website/issues/94

diff --git a/api/github.js b/api/github.js
index 0501a7b..4e8a00b 100644
--- a/api/github.js
+++ b/api/github.js
@@ -1,5 +1,5 @@
 import axios from 'axios';
-const END_POINT = "https://github.mybit.io";
+const END_POINT = "https://githubmybitio-tuhnxxkvld.now.sh";

 import getConfig from 'next/config';
```

**Comment by jjperezaguinaga** [comment]
@cryptomental Neat! Was about to do that ☺️

**Comment by jjperezaguinaga** [comment]
Looking good! Tested at https://testing-issue-94-fix-ddf-mybit-io-dev.now.sh/ with MyBitFoundation/MyBit-DDF.website#177.

Waiting on https://github.com/MyBitFoundation/github-proxy/pull/28, as we need to deploy the server first before we create the production patch for this one.

**Comment by cryptomental** [comment]
Great, thank you @jjperezaguinaga !

**Pull request merged**
